version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_build_tools//ci:run-bazel-rbe -- << parameters.command >>

  run-grakn-server:
    steps:
      - run-bazel-rbe:
          command: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir dist && tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start

jobs:
  build:
    machine: true
    working_directory: ~/biograkn
    steps:
      - install-bazel-linux-rbe
      - checkout
#      - run: bazel run @graknlabs_build_tools//checkstyle:test-coverage
      - run: bazel --host_jvm_args=-Xmx16g build //...

  test-assembly-linux-mock:
    machine: true
    working_directory: ~/biograkn
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir dist && tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start
      - run: bazel test //migrator:assemble-mock-test
      - run: ./dist/grakn-core-all-linux/grakn server stop
  test-assembly-mac-mock:
    machine: true
    working_directory: ~/biograkn
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: bazel build @graknlabs_grakn_core//:assemble-mac-zip
      - run: unzip bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-mac.zip -d bazel-genfiles/external/graknlabs_grakn_core/
      - run: nohup bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-mac/grakn server start
      - run: bazel test //migrator:assemble-mock-test
      - run: bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-mac/grakn server stop
  test-assembly-windows-mock:
    machine: true
    working_directory: ~/biograkn
    steps:
      - run: echo 'CI job placeholder'

  test-assembly-linux-full:
    machine: true
    working_directory: ~/biograkn
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir dist && tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start
      #      - run: bazel test test-assembly-linux-full
      - run: ./dist/grakn-core-all-linux/grakn server stop
  test-assembly-mac-full:
    machine: true
    working_directory: ~/biograkn
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: bazel build @graknlabs_grakn_core//:assemble-mac-zip
      - run: unzip bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-mac.zip -d bazel-genfiles/external/graknlabs_grakn_core/
      - run: nohup bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-mac/grakn server start
      #      - run: bazel test test-assembly-mac-full
      - run: bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-mac/grakn server stop
  test-assembly-windows-full:
    machine: true
    working_directory: ~/biograkn
    steps:
      - run: echo 'CI job placeholder'

  test-deployment-gcp:
    machine: true
    working_directory: ~/biograkn
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: pip install google-api-python-client paramiko pyyaml google-auth cryptography==2.4.2
      - run: GCP_DEPLOY_KEY=$GCP_DEPLOY_KEY_SNAPSHOT test/deployment/gcp.py

  release-approval:
    machine: true
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN_GRABL
          bazel run @graknlabs_build_tools//ci:release-approval

  deploy-github:
    machine: true
    working_directory: ~/biograkn
    steps:
      - run: echo 'CI job placeholder'

  deploy-gcp:
    machine: true
    working_directory: ~/biograkn
    steps:
      - run: echo 'CI job placeholder'

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: echo 'CI job placeholder'

workflows:
  biograkn:
    jobs:
      - build:
          filters:
            branches:
              ignore: biograkn-release-branch

      - test-assembly-linux-mock:
          filters:
            branches:
              ignore: biograkn-release-branch
      - test-assembly-mac-mock:
          filters:
            branches:
              ignore: biograkn-release-branch
#      - test-assembly-windows-mock:
#          filters:
#            branches:
#              only: master
#          requires:
#            - build
#            - test

      - test-assembly-linux-full:
          filters:
            branches:
              only: master
          requires:
            - build
      - test-assembly-mac-full:
          filters:
            branches:
              only: master
          requires:
            - build
#      - test-assembly-windows-full:
#          filters:
#            branches:
#              only: master
#          requires:
#            - build
#            - test

      - test-deployment-gcp:
          filters:
            branches:
              only: master
          requires:
            - test-assembly-linux-mock
            - test-assembly-mac-mock
#            - test-assembly-windows-mock
            - test-assembly-linux-full
            - test-assembly-mac-full
#            - test-assembly-windows-full
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - test-deployment-gcp

  biograkn-release:
    jobs:
      - test-assembly-linux-full:
          filters:
            branches:
              only: biograkn-release-branch
      - test-assembly-mac-full:
          filters:
            branches:
              only: biograkn-release-branch
#      - test-assembly-windows-full:
#          filters:
#            branches:
#              only: biograkn-release-branch

      - deploy-github:
          filters:
            branches:
              only: biograkn-release-branch
          requires:
            - test-assembly-linux-full
            - test-assembly-mac-full
#            - test-assembly-windows-full
      - deploy-approval:
          type: approval
          filters:
            branches:
              only: biograkn-release-branch
          requires:
            - deploy-github
      - deploy-gcp:
          filters:
            branches:
              only: biograkn-release-branch
          requires:
            - deploy-approval
            - test-assembly-linux-full

      - release-cleanup:
          filters:
            branches:
              only: biograkn-release-branch
          requires:
            - test-assembly-linux-full
            - test-assembly-mac-full
#            - test-assembly-windows-full
            - deploy-gcp
            - deploy-github
